# Upload some file
POST http://localhost:3333/api/files/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="body"; filename="vb"
Content-Type: application/json

{
  "image": "file.http"
}

--boundary
Content-Disposition: form-data; name="avatar"; filename="user-card-photo1.jpg"
Content-Type: image/png


< ../../../../download/fitfriends-build/img/content/user-card-photo1.jpg

--boundary
Content-Disposition: form-data; name="certificate"; filename="file.http"
Content-Type: image/png

< ./file.http

--boundary--

###

# Get file by ID
GET http://localhost:3333/api/files/649ae48544f2707c36f00e3d HTTP/1.1

###

