export type MockData = {
  textFeedbacks: string[],
  genders: string[],
  intervals: string[],
  locations: string[],
  emails: string[],
  orderStatuses: string[],
  paymentMethods: string[],
  purchaseTypes: string[],
  trainingLevels: string[],
  trainingTypes: string[],
  titles: string[],
  backgrounds: string[],
  descriptions: string[],
  demoVideos: string[],
  UserRoles: string[],
  names: string[],
  avatars: string[],
  password: string,
  userDescriptions: string[],
  certificates: string[],
  resumes: string[],
  usersGenders: string[],
  messages: string[]
}
