# Get user info
GET http://localhost:3333/api/user/6497e4e84c024e968c12fc9c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZTRlODRjMDI0ZTk2OGMxMmZjOWMiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjg3OTY3ODQ0LCJleHAiOjE2ODc5NjgyNjR9.X7rSDF4J01PUK_DsFsMmDyfZTXeMdV9ar431epErAUw

###
# Get users list
GET http://localhost:3333/api/user?limit=3&page=0&category=role&location=&trainingLevel=&trainingTypes=бег HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZTRlODRjMDI0ZTk2OGMxMmZjOWMiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjg3OTY3ODQ0LCJleHAiOjE2ODc5NjgyNjR9.X7rSDF4J01PUK_DsFsMmDyfZTXeMdV9ar431epErAUw

###
# Get users list
GET http://localhost:3333/api/user?limit=3&page=0&category=role&trainingTypes=бег HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZTRlODRjMDI0ZTk2OGMxMmZjOWMiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjg3OTY3ODQ0LCJleHAiOjE2ODc5NjgyNjR9.X7rSDF4J01PUK_DsFsMmDyfZTXeMdV9ar431epErAUw
