
@baseUrl = http://localhost:3333/api
@protocol = HTTP/1.1

# Get friends list
GET {{baseUrl}}/friend {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGFkMzI0ZmIzMTM3NDg3N2IxYjc4YTciLCJlbWFpbCI6ImMtdGVzdEBnbWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6ItCY0L3QtdGB0YHQsCDQpNGD0YDRgdC-0LLQsCIsImlhdCI6MTY4OTA3MjIzMiwiZXhwIjoxNjg5Njc3MDMyfQ.QuJXP__4KuESCwKUXGaThbMLbMCy9trkH-7sGO4oJws

###

# Add friend
POST http://localhost:3333/api/friend/649f9bfd7974b6f0298bc9a9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGFkMzI0ZmIzMTM3NDg3N2IxYjc4OTEiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiLQoNC-0LzQsNC9INCU0LzQuNGC0YDQuNC10LLQuNGHIiwiaWF0IjoxNjg5MDc0ODY4LCJleHAiOjE2ODk2Nzk2Njh9.mXTihBa6PgV_z4sfEVbfDtoXZhZszyZlIuE9fF2RHNo

###
# Delete friend
DELETE http://localhost:3333/api/friend/649f9bfd7974b6f0298bc9a9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGFkMzI0ZmIzMTM3NDg3N2IxYjc4OTEiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiLQoNC-0LzQsNC9INCU0LzQuNGC0YDQuNC10LLQuNGHIiwiaWF0IjoxNjg5MDc0ODY4LCJleHAiOjE2ODk2Nzk2Njh9.mXTihBa6PgV_z4sfEVbfDtoXZhZszyZlIuE9fF2RHNo
